POST http://localhost:5000/api/auth/register
Content-Type: application/json

{
    "username": "son78799@gmail.com",
    "password": "Son123@A",
    "name" : ""
}

###

POST http://localhost:5000/api/auth/login
Content-Type: application/json

{
    "username": "hihihi123456@gmail.com",
    "password": "Son123@A"
}


###

PUT http://localhost:5000/api/auth/update-profile
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY3MjQ2MmU4NTVkMjY5N2JjMGFlZjI2MCIsInVzZXJuYW1lIjoiaGloaWhpMTIzNDU2QGdtYWlsLmNvbSIsIm5hbWUiOiJoaWhpaGkxMjM0NTZAZ21haWwuY29tIiwiaW1hZ2UiOiJodHRwczovL2kucGluaW1nLmNvbS9vcmlnaW5hbHMvMmIvMGYvN2EvMmIwZjdhOTUzMzIzN2I3ZTliNDlmNjJiYTczYjk1ZGMuanBnIiwiZW1haWwiOiJoaWhpaGkxMjM0NTZAZ21haWwuY29tIiwicm9sZXMiOlsidXNlciJdLCJhZGRyZXNzIjoiIiwicGhvbmVOdW1iZXIiOiIiLCJjcmVhdGVkQXQiOiIyMDI0LTExLTAxVDA1OjExOjA0LjQyM1oiLCJpYXQiOjE3MzA3ODEzMDYsImV4cCI6MTczMDg1MzMwNn0.NoaoUjmi_1LhqedDumvz8y1TtQT_m9uk7vdDpC8EMdI

{
    "name": "Sơn Nguyễn",
    "image": "https://img.freepik.com/free-psd/3d-illustration-person-with-sunglasses_23-2149436188.jpg",
    "address": "106 Nguyễn Khiêm Ích, Trâu Quỳ GL",
    "phoneNumber": "0399790072",
    "email": ""
}

###

PUT http://localhost:5000/api/change-password
Content-Type: application/json
Authorization: Bearer "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY3MjQ2MmU4NTVkMjY5N2JjMGFlZjI2MCIsInVzZXJuYW1lIjoiaGloaWhpMTIzNDU2QGdtYWlsLmNvbSIsIm5hbWUiOiJoaWhpaGkxMjM0NTZAZ21haWwuY29tIiwiaW1hZ2UiOiJodHRwczovL2kucGluaW1nLmNvbS9vcmlnaW5hbHMvMmIvMGYvN2EvMmIwZjdhOTUzMzIzN2I3ZTliNDlmNjJiYTczYjk1ZGMuanBnIiwiZW1haWwiOiJoaWhpaGkxMjM0NTZAZ21haWwuY29tIiwicm9sZXMiOlsidXNlciJdLCJhZGRyZXNzIjoiIiwicGhvbmVOdW1iZXIiOiIiLCJjcmVhdGVkQXQiOiIyMDI0LTExLTAxVDA1OjExOjA0LjQyM1oiLCJpYXQiOjE3MzA2OTgxNjYsImV4cCI6MTczMDc3MDE2Nn0.FpQqm8UHyy6HaEeinDZ49Zw2-8ZG8H0ZffgXLKelxbw"

{
  "currentPassword": "Son123@Aa",
  "newPassword": "Son123@AA"
}

###

POST http://localhost:5000/api/category
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY2YzVkYzcxNWY2ZWZhMjQ1MGE5OTQ4MiIsInVzZXJuYW1lIjoibmd1eWVudmFuc29uMjYxMDIwMDBAZ21haWwuY29tIiwibmFtZSI6Ik5ndXnhu4VuIFPGoW4iLCJjYXJ0IjpbXSwiaW1hZ2UiOiIiLCJyb2xlcyI6WyJhZG1pbiJdLCJpYXQiOjE3MjQyNDkwOTYsImV4cCI6MTcyNDI1MjY5Nn0.UJulii0qQyjVrEPjt4kXM96O-ELONJ3JXmVJN2NlAzE

{
    "nameCategory": "Các món lẩu"
}

###

PUT http://localhost:5000/category/66badf9a2ef86e6ec15d4273
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY2YjYxZGRlMzY5MWQzZDE1YTRjN2RmOSIsInVzZXJuYW1lIjoiam9obl9kb2UxMjMiLCJpYXQiOjE3MjM1MjI3MDcsImV4cCI6MTcyMzUyNjMwN30.vhQgqexsMJRFMMu8ylC9kvOX9-cqj5FL-gc3FWJpWq8

{
    "nameCategory": "Các món gà tươi"
}

###

PUT http://localhost:5000/api/category/reorder-categories
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY2YzVkYzcxNWY2ZWZhMjQ1MGE5OTQ4MiIsInVzZXJuYW1lIjoibmd1eWVudmFuc29uMjYxMDIwMDBAZ21haWwuY29tIiwibmFtZSI6Ik5ndXnhu4VuIFPGoW4iLCJjYXJ0IjpbXSwiaW1hZ2UiOiIiLCJyb2xlcyI6WyJhZG1pbiJdLCJpYXQiOjE3Mjc4MzgzMjAsImV4cCI6MTcyNzkxMDMyMH0.KXNHIok00Zk_9Thx5wJGUtAD-X9DLXl2zxSmVbaVOMQ

{
    "orderList": ["66badf9a2ef86e6ec15d4273", "66f7f918631e3cc3d6bd9bb1", "66bae4cb0c12f647be1be5c6","66f7f988631e3cc3d6bd9bd3","66f7fa22631e3cc3d6bd9be9","66f7fad9631e3cc3d6bd9c00","66f7fb7c631e3cc3d6bd9c22","66f7fcfd631e3cc3d6bd9c43","66f7fe81631e3cc3d6bd9c77","66f94d3c631e3cc3d6bd9dca","66f94d4c631e3cc3d6bd9dd1","66fcdf49f7343874db06f851"]
}


###

GET http://localhost:5000/api/category
Content-Type: application/json


###

DELETE http://localhost:5000/category/66ba097c705eb3b9247dddb7
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY2YjYxZGRlMzY5MWQzZDE1YTRjN2RmOSIsInVzZXJuYW1lIjoiam9obl9kb2UxMjMiLCJpYXQiOjE3MjM1MjI3MDcsImV4cCI6MTcyMzUyNjMwN30.vhQgqexsMJRFMMu8ylC9kvOX9-cqj5FL-gc3FWJpWq8


###

DELETE http://localhost:5000/category/66b61d983691d3d15a4c7df7
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY2YjYxZGRlMzY5MWQzZDE1YTRjN2RmOSIsInVzZXJuYW1lIjoiam9obl9kb2UxMjMiLCJpYXQiOjE3MjM0NzA3NjEsImV4cCI6MTcyMzQ3NDM2MX0.5p9Fhc31IZ-1IUP_QJOPM7d-4ZdKdWQSkkcGFdXmkyk

###

POST http://localhost:5000/api/products
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY2YzVkYzcxNWY2ZWZhMjQ1MGE5OTQ4MiIsInVzZXJuYW1lIjoibmd1eWVudmFuc29uMjYxMDIwMDBAZ21haWwuY29tIiwibmFtZSI6Ik5ndXnhu4VuIFPGoW4iLCJjYXJ0IjpbXSwiaW1hZ2UiOiIiLCJyb2xlcyI6WyJhZG1pbiJdLCJpYXQiOjE3MjQyNDg0NjYsImV4cCI6MTcyNDI1MjA2Nn0.JBXv_CC380YtMKHLsEPVFM6pgtyMCgJd7usYsVd3e-k

{
  
}

###

POST http://localhost:5000/product/update-active
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY2YjYxZGRlMzY5MWQzZDE1YTRjN2RmOSIsInVzZXJuYW1lIjoiam9obl9kb2UxMjMiLCJpYXQiOjE3MjM1Mjc3ODEsImV4cCI6MTcyMzUzMTM4MX0.DvjyP2xi7hRVOJBR-kkYj0DSl1CNyQ5aUkHriQu_cRs

{
  "id": "66bae0602ef86e6ec15d4278",
  "isActive": true
}

###

GET http://localhost:5000/api/products

###

GET http://localhost:5000/api/category

###

GET http://localhost:5000/product/category/66bae4cb0c12f647be1be5c6
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY2YjYxZGRlMzY5MWQzZDE1YTRjN2RmOSIsInVzZXJuYW1lIjoiam9obl9kb2UxMjMiLCJpYXQiOjE3MjM1MjI3MDcsImV4cCI6MTcyMzUyNjMwN30.vhQgqexsMJRFMMu8ylC9kvOX9-cqj5FL-gc3FWJpWq8

###

POST http://localhost:5000/update-sale
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY2YjYxZGRlMzY5MWQzZDE1YTRjN2RmOSIsInVzZXJuYW1lIjoiam9obl9kb2UxMjMiLCJpYXQiOjE3MjM1Mjc3ODEsImV4cCI6MTcyMzUzMTM4MX0.DvjyP2xi7hRVOJBR-kkYj0DSl1CNyQ5aUkHriQu_cRs

{
  "ids": ["66bae4d90c12f647be1be5c9","66bae0602ef86e6ec15d4278"],
  "sale": 50
}

###

POST http://localhost:5000/update-new-product
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY2YjYxZGRlMzY5MWQzZDE1YTRjN2RmOSIsInVzZXJuYW1lIjoiam9obl9kb2UxMjMiLCJpYXQiOjE3MjM1Mjc3ODEsImV4cCI6MTcyMzUzMTM4MX0.DvjyP2xi7hRVOJBR-kkYj0DSl1CNyQ5aUkHriQu_cRs

{
  "ids": ["66bae4d90c12f647be1be5c9","66bae0602ef86e6ec15d4278"],
  "newProduct": false
}

###

POST http://localhost:5000/update-hot-product
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY2YjYxZGRlMzY5MWQzZDE1YTRjN2RmOSIsInVzZXJuYW1lIjoiam9obl9kb2UxMjMiLCJpYXQiOjE3MjM1Mjc3ODEsImV4cCI6MTcyMzUzMTM4MX0.DvjyP2xi7hRVOJBR-kkYj0DSl1CNyQ5aUkHriQu_cRs

{
  "ids": ["66bae4d90c12f647be1be5c9","66bae0602ef86e6ec15d4278"],
  "hotProduct": false
}

###

GET http://localhost:5000/api/order

###

GET http://localhost:5000/api/order/6724625d94bfff5a6746f6eb

###

POST http://localhost:5000/api/order
Content-Type: application/json

{
  "addressCustomers": "Tuan Hung Kim Thanh Hai Duong",
  "nameCustomers": "Son",
  "note": "",
  "phoneCustomers": "0399790072",
  "totalBill":1432000,
  "subTotal":1450000,
  "priceSaleProduct":18000,
  "subId":  "12345",
  "data": [
    {
      "currentPriceProduct": 640000,
      "idProduct": "66c9dd1f0ac82241b6c8d78f",
      "imgProduct": "",
      "nameProduct": "Gà luộc",
      "note": "Cực cay",
      "priceProduct": 160000,
      "quantity": 4,
      "sale": 0
    },
    {
      "currentPriceProduct": 320000,
      "idProduct": "66c9dd1f0ac82241b6c8d78g",
      "imgProduct": "",
      "nameProduct": "Gà rán",
      "note": "",
      "priceProduct": 160000,
      "quantity": 2,
      "sale": 0
    },
    {
      "currentPriceProduct": 180000,
      "idProduct": "66c9dd1f0ac82241b6c8d78h",
      "imgProduct": "",
      "nameProduct": "Gà rang muối",
      "note": "",
      "priceProduct": 180000,
      "quantity": 1,
      "sale": 10
    }
  ]
}

###

POST http://localhost:5000/api/order/delivered
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY2YzVkYzcxNWY2ZWZhMjQ1MGE5OTQ4MiIsInVzZXJuYW1lIjoibmd1eWVudmFuc29uMjYxMDIwMDBAZ21haWwuY29tIiwibmFtZSI6Ik5ndXnhu4VuIFPGoW4iLCJjYXJ0IjpbXSwiaW1hZ2UiOiIiLCJyb2xlcyI6WyJhZG1pbiJdLCJpYXQiOjE3MjcyNDAwMTgsImV4cCI6MTcyNzMxMjAxOH0.E4S38V-fVR37P4o-VsfOdiq1wNtW-e4RI2quU0cFQrg

{
  "id": "66f397e0e1f8e7f4684a6a86",
  "isDelivered" : true
}

###

POST http://localhost:5000/api/order/canceled
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY2YzVkYzcxNWY2ZWZhMjQ1MGE5OTQ4MiIsInVzZXJuYW1lIjoibmd1eWVudmFuc29uMjYxMDIwMDBAZ21haWwuY29tIiwibmFtZSI6Ik5ndXnhu4VuIFPGoW4iLCJjYXJ0IjpbXSwiaW1hZ2UiOiIiLCJyb2xlcyI6WyJhZG1pbiJdLCJpYXQiOjE3MjcyNDAwMTgsImV4cCI6MTcyNzMxMjAxOH0.E4S38V-fVR37P4o-VsfOdiq1wNtW-e4RI2quU0cFQrg

{
  "id": "66f397e0e1f8e7f4684a6a86",
  "isCanceled" : true
}

###

POST http://localhost:5000/api/order/preparing
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY2YzVkYzcxNWY2ZWZhMjQ1MGE5OTQ4MiIsInVzZXJuYW1lIjoibmd1eWVudmFuc29uMjYxMDIwMDBAZ21haWwuY29tIiwibmFtZSI6Ik5ndXnhu4VuIFPGoW4iLCJjYXJ0IjpbXSwiaW1hZ2UiOiIiLCJyb2xlcyI6WyJhZG1pbiJdLCJpYXQiOjE3MjcyNDAwMTgsImV4cCI6MTcyNzMxMjAxOH0.E4S38V-fVR37P4o-VsfOdiq1wNtW-e4RI2quU0cFQrg

{
  "id": "66f397e0e1f8e7f4684a6a86",
  "isPreparing" : true
}

###

POST http://localhost:5000/api/post
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY3MjQ2MjVkOTRiZmZmNWE2NzQ2ZjZlYiIsInVzZXJuYW1lIjoibmd1eWVudmFuc29uMjYxMDIwMDBAZ21haWwuY29tIiwibmFtZSI6IlZ1YSBnw6AgdMawxqFpIiwiaW1hZ2UiOiIiLCJlbWFpbCI6Im5ndXllbnZhbnNvbjI2MTAyMDAwQGdtYWlsLmNvbSIsInJvbGVzIjpbImFkbWluIl0sImFkZHJlc3MiOiIiLCJwaG9uZU51bWJlciI6IiIsImNyZWF0ZWRBdCI6IjIwMjQtMTEtMDNUMDU6MDM6MzguMDEwWiIsImlhdCI6MTczMDYxMDIxOCwiZXhwIjoxNzMwNjgyMjE4fQ.uXRQPdKgNIGxUwYKlOh9vadEvDlg7m2ZqGDBSroMlXQ

{
  "content": "Đây là một bài viết mẫu mới",
  "userId": "6724625d94bfff5a6746f6eb",
  "images": ["https://placehold.co/600x400/png","https://placehold.co/400"]
}

###

POST http://localhost:5000/api/post/67056750b54c6bd87cfc8e11/like-post
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY2YzZjNjEyZjUxNDdiM2MzODJhZjdhNCIsInVzZXJuYW1lIjoiaGloaWhpMTIzNDU2QGdtYWlsLmNvbSIsIm5hbWUiOiJoaWhpaGkxMjM0NTZAZ21haWwuY29tIiwiY2FydCI6W10sImltYWdlIjoiIiwicm9sZXMiOlsidXNlciJdLCJpYXQiOjE3Mjg0NTIzNDcsImV4cCI6MTcyODUyNDM0N30.X4NzdW0TgiPs23Sly1jobRuoMrUVT-FJVbGVGNJUYPA

{
  "userId":"66c5dc715f6efa2450a99482"
}

###

GET http://localhost:5000/api/post
Content-Type: application/json

###

POST http://localhost:5000/api/comment
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY3MjQ2MjVkOTRiZmZmNWE2NzQ2ZjZlYiIsInVzZXJuYW1lIjoibmd1eWVudmFuc29uMjYxMDIwMDBAZ21haWwuY29tIiwibmFtZSI6IlZ1YSBnw6AgdMawxqFpIiwiaW1hZ2UiOiIiLCJlbWFpbCI6Im5ndXllbnZhbnNvbjI2MTAyMDAwQGdtYWlsLmNvbSIsInJvbGVzIjpbImFkbWluIl0sImFkZHJlc3MiOiIiLCJwaG9uZU51bWJlciI6IiIsImNyZWF0ZWRBdCI6IjIwMjQtMTEtMDNUMDU6MDM6MzguMDEwWiIsImlhdCI6MTczMDYxMDIxOCwiZXhwIjoxNzMwNjgyMjE4fQ.uXRQPdKgNIGxUwYKlOh9vadEvDlg7m2ZqGDBSroMlXQ

{
  "postId": "6727795422449becb5d8afc0",
  "contentCmt": "Đây là comment chính",
  "userId": "6724625d94bfff5a6746f6eb",
  "imageCmt": "https://placehold.co/600x400/png"
}

###

POST http://localhost:5000/api/comment
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY3MjQ2MjVkOTRiZmZmNWE2NzQ2ZjZlYiIsInVzZXJuYW1lIjoibmd1eWVudmFuc29uMjYxMDIwMDBAZ21haWwuY29tIiwibmFtZSI6IlZ1YSBnw6AgdMawxqFpIiwiaW1hZ2UiOiIiLCJlbWFpbCI6Im5ndXllbnZhbnNvbjI2MTAyMDAwQGdtYWlsLmNvbSIsInJvbGVzIjpbImFkbWluIl0sImFkZHJlc3MiOiIiLCJwaG9uZU51bWJlciI6IiIsImNyZWF0ZWRBdCI6IjIwMjQtMTEtMDNUMDU6MDM6MzguMDEwWiIsImlhdCI6MTczMDYxMDIxOCwiZXhwIjoxNzMwNjgyMjE4fQ.uXRQPdKgNIGxUwYKlOh9vadEvDlg7m2ZqGDBSroMlXQ

{
  "postId": "6727795422449becb5d8afc0",
  "contentCmt": "Trả lời bình luận của Nguyễn Sơn",
  "userId": "6724625d94bfff5a6746f6eb",
  "imageCmt": "https://placehold.co/600x400/png",
  "parentId": "6727c99e22449becb5d8b04f",
  "replyToUserId": "6724625d94bfff5a6746f6eb"
}

###

GET http://localhost:5000/api/comment/67055921dec42cf4284f30e7





